test_task:
  container:
    image: golang:latest
    additional_containers:
      - name: azurite
        image: mcr.microsoft.com/azure-storage/azurite
        port: 10000

  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  get_script: go get -t -v ./...
  vet_script: go vet -v ./...
  test_script: go test -v ./...

deploy_docker_builder:
  only_if: $CIRRUS_BRANCH == "master"
  environment:
    GITHUB_TOKEN: ENCRYPTED[!82ed873afdf627284305afef4958c85a8f73127b09978a9786ac521559630ea6c9a5ab6e7f8315abf9ead09b6eff6eae!]
  login_script: echo $GITHUB_TOKEN | docker login ghcr.io -u fkorotkov --password-stdin
  build_script:
    - docker --version
    - docker build --tag ghcr.io/cirruslabs/azure-blob-storage-proxy:latest .
  push_script: docker push ghcr.io/cirruslabs/azure-blob-storage-proxy:latest
